name: Linter

#Usually you would use this for pull requests or for pushing to one branch and having it push to another but here we are just pushing to main

on:
  push:
    branches:    
      - main
      
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Change Working Directory
        run: cd Source
      
      - name: Lint Codebase
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CPP: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    
